services:
    php:
        default: true
        image: tugboatqa/php:7.3-apache
        depends: mysql
        commands:
            init:

                # Install prerequisite packages
                - apt-get update
                - apt-get install -y rsync jq

                # Turn on URL rewriting.
                - a2enmod rewrite substitute
                - cp .tugboat/vhost.conf /etc/apache2/sites-available/000-default.conf

                # Install PHP mysqli extension
                - docker-php-ext-install mysqli

                # Install wp-cli
                - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                - chmod +x wp-cli.phar
                - mv wp-cli.phar /usr/local/bin/wp

                # Link the docroot
                - ln -snf "${TUGBOAT_ROOT}/docroot" "${DOCROOT}"

                # Configure wordpress to work with tugboat
                - wp --allow-root --path="${DOCROOT}" config create --dbhost=mysql --dbname=tugboat --dbuser=tugboat --dbpass=tugboat --force

                # Update permalinks to remove the index.php.
                - wp --allow-root --path="${DOCROOT}" option set permalink_structure /%postname%/
                - wp --allow-root --path="${DOCROOT}" rewrite flush --hard

            update:

                # Import uploads
                - curl -L "https://www.dropbox.com/s/ufn5e3qe3sisdks/demo-wordpress-uploads.tar.gz?dl=0" > /tmp/uploads.tar.gz
                - tar -C /tmp -zxf /tmp/uploads.tar.gz
                - rsync -av --delete /tmp/uploads/ "${TUGBOAT_ROOT}/docroot/wp-content/uploads/"

                # Cleanup
                - apt-get clean
                - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

            build: |
                if [ "x${TUGBOAT_BASE_PREVIEW}" != "x" ]; then
                    wp --allow-root --path="${DOCROOT}" search-replace "${TUGBOAT_BASE_PREVIEW_URL_HOST}" "${TUGBOAT_SERVICE_URL_HOST}" --skip-columns=guid
                else
                    wp --allow-root --path="${DOCROOT}" search-replace 'main-hbpfbyk632i25rgdo9caeoo9oxs4mrtd.tugboat.qa' "${TUGBOAT_SERVICE_URL_HOST}" --skip-columns=guid
                fi

            # Create a punchlist page when a new preview is online or cloned.
            online:
                - .tugboat/punchlist-page-create.sh | jq
            clone:
                - .tugboat/punchlist-page-create.sh | jq

        urls:
            - /
            - /about/
            - /contact/
            - /tugboat-engines-typically-produce-680-to-3400-hp/

        visualdiff:
            threshold: 90

    mysql:
        image: tugboatqa/mysql:5
        commands:
            update:
                - curl -L "https://www.dropbox.com/s/sabj5vq711bhst2/demo-wordpress-database.sql.gz?dl=0" > /tmp/database.sql.gz
                - zcat /tmp/database.sql.gz | mysql tugboat
                - rm /tmp/database.sql.gz
